<style>
    .docs{display:grid;gap:20px;color:#d1d5db}.docs-card{padding:24px;border:1px solid #374151;border-radius:12px;background:#1f2937}.docs-hero{background:linear-gradient(135deg,#312e81,#1f2937 62%)}.docs h1,.docs h2{margin:0;color:#fff}.docs h1{font-size:28px}.docs h2{font-size:18px}.docs h3{margin:18px 0 6px;color:#f3f4f6;font-size:15px}.docs p{margin:8px 0 0;font-size:14px;line-height:1.65}.docs ul,.docs ol{margin:10px 0 0;padding-left:20px;font-size:14px;line-height:1.75}.docs-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.docs code{padding:2px 5px;border-radius:4px;background:#111827;color:#c4b5fd}.docs-note{margin-top:16px!important;padding:12px 14px;border-left:3px solid #f59e0b;border-radius:0 6px 6px 0;background:rgb(245 158 11 / .08)}@media(max-width:700px){.docs-grid{grid-template-columns:1fr}.docs-card{padding:18px}}
</style>

<section class="docs">
    <div class="docs-card docs-hero"><p style="margin:0;color:#c4b5fd;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase">Pixel Store</p><h1>Documentacao do sistema</h1><p>Guia da versao atual da loja e do painel administrativo.</p></div>

    <div class="docs-grid">
        <article class="docs-card"><h2>Loja publica</h2><ul><li><strong>Inicio:</strong> banner principal e acesso ao catalogo.</li><li><strong>Ver Produtos:</strong> lista 30 produtos e filtra por Perifericos, Audio e Hardware.</li><li><strong>Detalhes:</strong> cada item tem pagina, quantidade e botao para carrinho.</li><li><strong>Contato:</strong> usa o email <code>meuovinho06@gmail.com</code>.</li></ul></article>
        <article class="docs-card"><h2>Conta de cliente</h2><ul><li>O icone de usuario abre as abas <strong>Login</strong> e <strong>Register</strong>.</li><li>Cadastro: nome, email valido e senha com no minimo 6 caracteres.</li><li>Login e obrigatorio para adicionar itens e finalizar pedidos.</li><li>O avatar da conta mostra os dados do cliente e o botao <strong>Desconectar</strong>.</li></ul></article>
    </div>

    <article class="docs-card"><h2>Fluxo de compra</h2><ol><li>O cliente abre um produto e define a quantidade.</li><li>Sem sessao, e encaminhado para Login/Register.</li><li>No carrinho, pode remover itens e visualizar o total.</li><li>Ao finalizar, informa endereco completo, cidade e CEP.</li><li>A confirmacao limpa o carrinho da sessao e mostra a mensagem de pedido finalizado.</li></ol><p class="docs-note"><strong>Importante:</strong> nao ha Pix, cartao, calculo de frete nem gateway de pagamento. O pedido e uma confirmacao simulada na sessao do navegador.</p></article>

    <div class="docs-grid">
        <article class="docs-card"><h2>Admin: categorias e produtos</h2><h3>Categorias</h3><p>A aba Categorias permite criar, editar e remover agrupamentos. Para cadastrar um produto, uma categoria existente deve ser selecionada.</p><h3>Produtos</h3><p>A aba Produtos cadastra e remove itens usando nome, preco, categoria, imagem e descricao.</p><ul><li>Imagens aceitas: JPG, PNG, WEBP e GIF.</li><li>Uploads sao salvos em <code>uploads/produtos/</code>.</li><li>As categorias exibidas na vitrine vem do campo categoria de cada produto salvo.</li></ul></article>
        <article class="docs-card"><h2>Admin: equipe e fornecedores</h2><h3>Equipe / Usuarios</h3><p>Lista, cadastra, edita e remove administradores. O acesso e feito por <code>admin/login.php</code>.</p><h3>Fornecedores</h3><p>Permite cadastrar, listar, editar e remover fornecedores com nome, CNPJ, telefone e endereco comercial.</p><p class="docs-note"><strong>Dashboard:</strong> a aba esta presente, mas o arquivo atual nao possui indicadores nem conteudo.</p></article>
    </div>

    <article class="docs-card"><h2>Arquivos e armazenamento</h2><ul><li><code>index.php</code>: vitrine, sessao do cliente, carrinho, login e checkout.</li><li><code>pages/</code>: telas publicas, como produtos, detalhes, carrinho, login e checkout.</li><li><code>admin/</code>: login e painel administrativo.</li><li><code>includes/banco_ficticio.php</code>: funcoes de leitura e gravacao.</li><li><code>data/produtos.json</code>, <code>categorias.json</code>, <code>clientes.json</code>, <code>usuarios.json</code> e <code>fornecedores.json</code>: dados locais em JSON.</li></ul><p class="docs-note"><strong>Servidor:</strong> o PHP precisa ter permissao de escrita em <code>data/</code> e <code>uploads/produtos/</code> para que os cadastros funcionem.</p></article>
</section>
